"use client";
import { useState } from "react";
import type { FixProposal } from "@/lib/fix-generator";
import { Panel, SectionHeader, Pill, ExternalLink } from "@/components/ui";
export function FixCard({ fix }: { fix: FixProposal }) {
  const [showDiff, setShowDiff] = useState(false);
  const pt = { critical: "alert", high: "warn", medium: "muted", low: "muted" } as const;
  return (<Panel><SectionHeader title={fix.title} right={<div className="flex items-center gap-2"><Pill tone={pt[fix.priority]}>{fix.priority}</Pill>{fix.isSafeAutoFix && <Pill tone="ok">safe auto-fix</Pill>}</div>} /><div className="space-y-3 px-5 py-4 text-sm"><div><p className="text-[11px] uppercase tracking-wider text-text-dim">Problem</p><p className="text-text-muted">{fix.problemExplanation}</p></div><div><p className="text-[11px] uppercase tracking-wider text-text-dim">Root cause</p><p className="text-text-muted">{fix.rootCause}</p></div><div><p className="text-[11px] uppercase tracking-wider text-text-dim">Affected files</p><div className="flex flex-wrap gap-1">{fix.affectedFiles.map((f) => <code key={f} className="rounded border border-border bg-bg-elevated px-1.5 py-0.5 text-xs text-accent">{f}</code>)}</div></div><div className="flex items-center gap-2"><p className="text-[11px] uppercase tracking-wider text-text-dim">Confidence</p><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-bg-elevated"><div className="h-full rounded-full bg-accent" style={{ width: `${fix.confidence}%` }} /></div><span className="text-xs text-text">{fix.confidence}%</span></div><button onClick={() => setShowDiff(!showDiff)} className="text-xs text-accent hover:underline">{showDiff ? "Hide patch" : "Show patch diff"}</button>{showDiff && <pre className="overflow-x-auto rounded-lg border border-border bg-bg p-3 text-xs text-text-muted"><code>{fix.patchDiff}</code></pre>}<div><p className="text-[11px] uppercase tracking-wider text-text-dim">Test suggestions</p><p className="text-text-muted whitespace-pre-line text-xs">{fix.testSuggestions}</p></div><div className="flex items-start gap-2"><p className="text-[11px] uppercase tracking-wider text-text-dim shrink-0">Regression risk</p><p className="text-xs text-warn">{fix.regressionRisk}</p></div><p className="text-[11px] text-text-dim">{fix.explainability}</p><div className="flex items-center gap-2 pt-1"><ExternalLink href={fix.issueUrl}>View issue #{fix.issueNumber}</ExternalLink></div></div></Panel>);
}
