"use client";
import type { ClusteredIssue, DuplicateGroup } from "@/lib/analytics";
import { Panel, SectionHeader, Pill, ExternalLink } from "@/components/ui";
import { relTime } from "@/lib/formatters";
const CC: Record<string,string> = { bug: "#c94040", enhancement: "#2d8659", question: "#b8730a", documentation: "#6d5cae", other: "#8b95a5" };
const PT = { critical: "alert", high: "warn", medium: "muted", low: "muted" } as const;
export function IssuesInsights({ issues, duplicates }: { issues: ClusteredIssue[]; duplicates: DuplicateGroup[] }) {
  const bc = issues.reduce((a,i)=>{a[i.classification]=(a[i.classification]??0)+1;return a;},{} as Record<string,number>);
  return (<div className="space-y-4"><Panel><SectionHeader title="Issue Classification" sub={`${issues.length} open issues classified.`} /><div className="grid grid-cols-2 gap-3 px-5 py-4 md:grid-cols-5">{Object.entries(bc).map(([c,n])=>(<div key={c} className="rounded-lg border border-border bg-bg-elevated px-3 py-2.5"><p className="text-[10px] uppercase tracking-wider text-text-dim">{c}</p><p className="text-2xl font-semibold" style={{color:CC[c]}}>{n}</p></div>))}</div></Panel>{duplicates.length>0 && <Panel><SectionHeader title="Duplicate Issues" sub={`${duplicates.length} group${duplicates.length===1?"":"s"} detected.`} /><ul className="divide-y divide-border">{duplicates.map((g)=>(<li key={g.primary} className="px-5 py-3 text-sm"><div className="flex items-center gap-2"><Pill tone="warn">duplicate</Pill><span className="text-text-muted">Primary #{g.primary}</span></div><ul className="mt-1 ml-4 space-y-0.5">{g.duplicates.map((d)=>(<li key={d.number} className="flex items-center gap-2 text-xs text-text-dim"><span>#{d.number} {d.title}</span><Pill tone="muted">{d.confidence}%</Pill></li>))}</ul></li>))}</ul></Panel>}<Panel><SectionHeader title="Prioritized Issues" sub="Critical first." /><ul className="divide-y divide-border">{issues.slice(0,30).map((i)=>(<li key={i.number} className="flex items-start gap-3 px-5 py-3 text-sm"><Pill tone={PT[i.priority]}>{i.priority}</Pill><div className="min-w-0 flex-1"><ExternalLink href={i.htmlUrl}>#{i.number} {i.title}</ExternalLink><p className="text-[11px] text-text-dim">{i.rationale} · {i.comments} comments · {relTime(i.updatedAt)}</p></div><Pill tone="muted" className="capitalize">{i.classification}</Pill></li>))}{issues.length===0 && <li className="px-5 py-4 text-xs text-text-muted">No open issues.</li>}</ul></Panel></div>);
}
