import type { IssueData, PullData, CommitData, Contributor, RepoMeta } from "@/lib/github";
export type IssueClass = "bug" | "enhancement" | "question" | "documentation" | "other";
export type Severity = "critical" | "high" | "medium" | "low";
export type Priority = "critical" | "high" | "medium" | "low";
export interface ClusteredIssue { number: number; title: string; classification: IssueClass; severity: Severity; priority: Priority; summary: string; isDuplicateOf: number | null; duplicateConfidence: number; labels: string[]; comments: number; createdAt: string; updatedAt: string; htmlUrl: string; authorLogin: string | null; rationale: string; }
export interface DuplicateGroup { primary: number; duplicates: { number: number; title: string; confidence: number }[]; }
export interface PRRiskAssessment { number: number; title: string; riskLevel: "low" | "medium" | "high"; riskFlags: string[]; missingTests: boolean; edgeCaseRisk: boolean; additions: number; deletions: number; changedFiles: number; htmlUrl: string; authorLogin: string | null; summary: string; }
export interface ContributorAnalytics { login: string; avatarUrl: string; htmlUrl: string; commits: number; linesAdded: number; linesRemoved: number; criticalModuleOwner: boolean; topContributor: boolean; busFactorScore: number; contributionPct: number; }
export interface CodebaseSignal { path: string; riskScore: number; reasons: string[]; changeCount30d: number; lastChangedAt: string | null; linkedIssueNumbers: number[]; }
export interface ActivityBucket { date: string; commits: number; additions: number; deletions: number; issuesOpened: number; issuesClosed: number; prsOpened: number; prsMerged: number; }
export interface AnalyticsResult { clusteredIssues: ClusteredIssue[]; duplicateGroups: DuplicateGroup[]; prRisks: PRRiskAssessment[]; contributorAnalytics: ContributorAnalytics[]; codebaseSignals: CodebaseSignal[]; activityBuckets: ActivityBucket[]; busFactor: number; releaseReadiness: { score: number; band: "safe" | "moderate" | "high-risk"; summary: string }; }
const CLASS_RX: Record<IssueClass, RegExp> = { bug: /\b(bug|crash|error|fail|broken|defect|regression|panic|exception)\b/i, enhancement: /\b(feature|enhancement|request|proposal|improvement|add|support|allow|enable)\b/i, question: /\b(question|how do|how to|help|clarification|confused|explain)\b/i, documentation: /\b(doc|docs|documentation|readme|guide|tutorial|typo)\b/i, other: /.^/ };
const SEV_RX: Record<Severity, RegExp> = { critical: /\b(critical|p0|severity.?1|blocker|security|cve|vulnerability|crash)\b/i, high: /\b(high|p1|severity.?2|major|urgent|important|broken)\b/i, medium: /\b(medium|p2|severity.?3|normal|minor)\b/i, low: /\b(low|p3|severity.?4|trivial|cosmetic|cleanup)\b/i };
const CAT_LABELS: Record<IssueClass, string> = { bug: "Bug", enhancement: "Enhancement", question: "Question", documentation: "Documentation", other: "Other" };
function classify(i: IssueData): IssueClass { const b = i.title + " " + i.labels.map((l) => l.name).join(" "); for (const c of ["bug","enhancement","question","documentation"] as IssueClass[]) if (CLASS_RX[c].test(b)) return c; return "other"; }
function sev(i: IssueData): Severity { const b = i.title + " " + i.labels.map((l) => l.name).join(" "); for (const s of ["critical","high","medium","low"] as Severity[]) if (SEV_RX[s].test(b)) return s; if (i.comments >= 20) return "high"; if (i.comments >= 5) return "medium"; return "low"; }
function pri(c: IssueClass, s: Severity, cm: number, age: number): Priority { const bi: Record<IssueClass, number> = { bug: 5, enhancement: 3, question: 1, documentation: 2, other: 2 }; const sw: Record<Severity, number> = { critical: 10, high: 7, medium: 4, low: 1 }; let v = bi[c] + sw[s]; if (cm >= 10) v += 2; if (age > 90) v += 1; if (v >= 12) return "critical"; if (v >= 8) return "high"; if (v >= 4) return "medium"; return "low"; }
function summ(t: string, m = 140): string { const c = t.replace(/\r?\n/g, " ").replace(/\s+/g, " ").trim(); return c.length <= m ? c || "(no description)" : c.slice(0, m - 3).trimEnd() + "\u2026"; }
function days(d: string): number { return Math.max(0, (Date.now() - Date.parse(d)) / 86_400_000); }
function sim(a: string, b: string): number { const ta = new Set(a.toLowerCase().split(/\s+/).filter((t) => t.length > 3)); const tb = new Set(b.toLowerCase().split(/\s+/).filter((t) => t.length > 4)); if (!ta.size || !tb.size) return 0; let n = 0; for (const t of ta) if (tb.has(t)) n++; return (2 * n) / (ta.size + tb.size); }
function findDups(issues: IssueData[]): DuplicateGroup[] { const open = issues.filter((i) => i.state === "open" && !i.pull_request); const groups: DuplicateGroup[] = []; const seen = new Set<number>(); for (let i = 0; i < open.length; i++) { if (seen.has(open[i]!.number)) continue; const d: { number: number; title: string; confidence: number }[] = []; for (let j = i + 1; j < open.length; j++) { if (seen.has(open[j]!.number)) continue; const s = sim(open[i]!.title, open[j]!.title); if (s >= 0.6) { d.push({ number: open[j]!.number, title: open[j]!.title, confidence: Math.round(s * 100) }); seen.add(open[j]!.number); } } if (d.length) { seen.add(open[i]!.number); groups.push({ primary: open[i]!.number, duplicates: d }); } } return groups; }
function prRisk(p: PullData): PRRiskAssessment { const f: string[] = []; const age = days(p.created_at), idle = days(p.updated_at); if (idle > 30) f.push(`Stale (${Math.round(idle)}d)`); if (p.draft) f.push("Draft"); if (age > 60) f.push(`Long-lived (${Math.round(age)}d)`); let rl: "low" | "medium" | "high" = "low"; if (f.length >= 3) rl = "high"; else if (f.length >= 1) rl = "medium"; return { number: p.number, title: p.title, riskLevel: rl, riskFlags: f, missingTests: false, edgeCaseRisk: false, additions: 0, deletions: 0, changedFiles: 1, htmlUrl: p.html_url, authorLogin: p.user?.login ?? null, summary: `${f.length} signal${f.length === 1 ? "" : "s"}: ${f.join(", ") || "clean"}` }; }
function contribsAnalytics(c: Contributor[]): ContributorAnalytics[] { const tot = c.reduce((s, x) => s + x.contributions, 0); return [...c].sort((a, b) => b.contributions - a.contributions).slice(0, 20).map((x, i) => { const pct = tot > 0 ? Math.round((x.contributions / tot) * 100) : 0; return { login: x.login, avatarUrl: x.avatar_url, htmlUrl: x.html_url, commits: x.contributions, linesAdded: 0, linesRemoved: 0, criticalModuleOwner: pct > 25, topContributor: i < 3, busFactorScore: tot > 0 ? Math.round((x.contributions / tot) * 100) / 100 : 0, contributionPct: pct }; }); }
function codebaseSignals(cm: CommitData[]): CodebaseSignal[] { const fm = new Map<string, { changes: number; lastDate: string | null; links: number[] }>(); for (const c of cm) { const m = (c.commit?.message ?? "").match(/\b([\w-]+\/(?:src|lib|components|api|routes|services|utils|core)\/[\w/.-]+)\b/); if (m) { const p = m[1]!; const e = fm.get(p) ?? { changes: 0, lastDate: null, links: [] }; e.changes++; const d = c.commit?.author?.date; if (d && (!e.lastDate || d > e.lastDate)) e.lastDate = d; fm.set(p, e); } } const out: CodebaseSignal[] = []; for (const [p, d] of fm) { const r: string[] = []; let s = 0; if (d.changes >= 5) { s += 30; r.push(`Changed ${d.changes}x`); } if (d.changes >= 10) { s += 20; r.push("Hotspot"); } if (d.lastDate && days(d.lastDate) < 7 && d.changes > 2) { s += 15; r.push("Recently modified"); } s = Math.min(100, s); if (s > 0 || d.changes > 0) out.push({ path: p, riskScore: s, reasons: r.length ? r : ["Tracked"], changeCount30d: d.changes, lastChangedAt: d.lastDate, linkedIssueNumbers: d.links }); } return out.sort((a, b) => b.riskScore - a.riskScore).slice(0, 15); }
function activityBuckets(cm: CommitData[], is: IssueData[], ps: PullData[]): ActivityBucket[] { const now = Date.now(); const b: ActivityBucket[] = []; for (let d = 29; d >= 0; d--) b.push({ date: new Date(now - d * 86_400_000).toISOString().slice(0, 10), commits: 0, additions: 0, deletions: 0, issuesOpened: 0, issuesClosed: 0, prsOpened: 0, prsMerged: 0 }); for (const c of cm) { const ts = Date.parse(c.commit?.author?.date ?? ""); if (isNaN(ts)) continue; const i = 29 - Math.floor((now - ts) / 86_400_000); if (i >= 0 && i < 30) b[i]!.commits++; } for (const i of is) { if (i.pull_request) continue; const o = 29 - Math.floor((now - Date.parse(i.created_at)) / 86_400_000); if (o >= 0 && o < 30) b[o]!.issuesOpened++; if (i.closed_at) { const c = 29 - Math.floor((now - Date.parse(i.closed_at)) / 86_400_000); if (c >= 0 && c < 30) b[c]!.issuesClosed++; } } for (const p of ps) { const o = 29 - Math.floor((now - Date.parse(p.created_at)) / 86_400_000); if (o >= 0 && o < 30) b[o]!.prsOpened++; if (p.merged_at) { const m = 29 - Math.floor((now - Date.parse(p.merged_at)) / 86_400_000); if (m >= 0 && m < 30) b[m]!.prsMerged++; } } return b; }
function busFactor(c: Contributor[]): number { if (!c.length) return 0; const t = c.reduce((s, x) => s + x.contributions, 0); if (!t) return 0; let cu = 0; for (let i = 0; i < c.length; i++) { cu += c[i]!.contributions; if (cu / t >= 0.5) return i + 1; } return c.length; }
export function runAnalytics(repo: RepoMeta, issues: IssueData[], pulls: PullData[], commits: CommitData[], contribs: Contributor[]): AnalyticsResult {
  const open = issues.filter((i) => i.state === "open" && !i.pull_request);
  const dg = findDups(issues); const dn = new Set<number>(); for (const g of dg) for (const d of g.duplicates) dn.add(d.number);
  const ci: ClusteredIssue[] = open.map((i) => { const c = classify(i); const s = sev(i); const a = days(i.created_at); const p = pri(c, s, i.comments, a); const dof = dn.has(i.number) ? dg.find((g) => g.duplicates.some((d) => d.number === i.number))?.primary ?? null : null; const dc = dof ? dg.find((g) => g.primary === dof)?.duplicates.find((d) => d.number === i.number)?.confidence ?? 0 : 0; return { number: i.number, title: i.title, classification: c, severity: s, priority: p, summary: summ(i.title), isDuplicateOf: dof, duplicateConfidence: dc, labels: i.labels.map((l) => l.name), comments: i.comments, createdAt: i.created_at, updatedAt: i.updated_at, htmlUrl: i.html_url, authorLogin: i.user?.login ?? null, rationale: `${CAT_LABELS[c]} \u00b7 ${s} severity \u00b7 ${p} priority${dof ? ` \u00b7 dup of #${dof}` : ""}` }; }).sort((a, b) => { const o = { critical: 0, high: 1, medium: 2, low: 3 }; return o[a.priority] - o[b.priority]; });
  const pr = pulls.map((p) => prRisk(p)).sort((a, b) => (a.riskLevel === "high" ? 0 : a.riskLevel === "medium" ? 1 : 2) - (b.riskLevel === "high" ? 0 : b.riskLevel === "medium" ? 1 : 2));
  const ca = contribsAnalytics(contribs); const cs = codebaseSignals(commits); const ab = activityBuckets(commits, issues, pulls); const bf = busFactor(contribs);
  const cc = ci.filter((i) => i.severity === "critical").length; const hp = ci.filter((i) => i.priority === "high" || i.priority === "critical").length; const dc2 = dg.reduce((s, g) => s + g.duplicates.length, 0);
  let score = 100; score -= Math.min(40, cc * 12); score -= Math.min(20, Math.max(0, open.length - 20) * 0.5); score -= Math.min(15, hp * 3); score -= Math.min(10, dc2 * 2); score = Math.max(0, Math.min(100, Math.round(score)));
  const band = score >= 70 ? "safe" : score >= 50 ? "moderate" : "high-risk";
  const summary = `Project is ${score}% ready for release${band !== "safe" ? ` \u2014 ${band === "high-risk" ? "high" : "moderate"} risk${cc > 0 ? ` with ${cc} critical issue${cc === 1 ? "" : "s"}` : ""}` : ""}`;
  return { clusteredIssues: ci, duplicateGroups: dg, prRisks: pr, contributorAnalytics: ca, codebaseSignals: cs, activityBuckets: ab, busFactor: bf, releaseReadiness: { score, band, summary } };
}
