import { notFound } from "next/navigation";
import { getRepo, getRecentIssues, getRecentPulls, getRecentCommits, getContributors, getLanguages, GithubError } from "@/lib/github";
import { generateInsights } from "@/lib/insights";
import { runAnalytics } from "@/lib/analytics";
import { generateFixes } from "@/lib/fix-generator";
import { RepoHeader } from "@/components/repo-header";
import { Panel, SectionHeader, ExternalLink } from "@/components/ui";
import { VerdictCard } from "@/components/verdict-card";
import { IssuesInsights } from "@/components/issues-insights";
import { PRInsights } from "@/components/pr-insights";
import { ContributorsInsights } from "@/components/contributors-insights";
import { ActivityTrends } from "@/components/activity-trends";
import { CodebaseSignals } from "@/components/codebase-signals";
import { SecurityPanel } from "@/components/security-panel";
import { LanguageBar } from "@/components/language-bar";
import { FixCard } from "@/components/fix-card";
import { InsightCard } from "@/components/insight-card";
import { relTime } from "@/lib/formatters";

interface Props { params: Promise<{ owner: string; name: string }>; }
export async function generateMetadata({ params }: Props) { const { owner, name } = await params; return { title: `${owner}/${name} \u2014 TraceRoot Report` }; }

export default async function SharePage({ params }: Props) {
  const { owner, name } = await params;
  let r;
  try { r = await getRepo({ owner, name, fullName: `${owner}/${name}` }); }
  catch (e) { if (e instanceof GithubError) return notFound(); throw e; }

  const [issues, pulls, commits, contribs, langs] = await Promise.all([
    getRecentIssues({ owner, name, fullName: r.full_name }),
    getRecentPulls({ owner, name, fullName: r.full_name }),
    getRecentCommits({ owner, name, fullName: r.full_name }),
    getContributors({ owner, name, fullName: r.full_name }).catch(() => []),
    getLanguages({ owner, name, fullName: r.full_name }).catch(() => ({} as Record<string, number>)),
  ]);

  const insights = generateInsights(r, issues, pulls, commits, contribs);
  const analytics = runAnalytics(r, issues, pulls, commits, contribs);
  const fixes = generateFixes(analytics.clusteredIssues, analytics.codebaseSignals);

  return (
    <div className="min-h-screen bg-bg pb-12">
      <div className="border-b border-border bg-panel"><div className="mx-auto max-w-5xl px-6 py-3 flex items-center justify-between"><span className="text-sm font-semibold text-text">TraceRoot Report</span><span className="text-xs text-text-dim">Public share \u00b7 {relTime(new Date().toISOString())}</span></div></div>
      <div className="mx-auto max-w-5xl px-6 py-6 space-y-5">
        <RepoHeader r={r} />
        <VerdictCard score={analytics.releaseReadiness.score} band={analytics.releaseReadiness.band} summary={analytics.releaseReadiness.summary} />
        <Panel><SectionHeader title="Insights" right={<span className="text-[11px] text-text-dim">{insights.length} detected</span>} />{insights.length === 0 ? <p className="px-5 py-4 text-xs text-text-muted">No signals detected.</p> : <div className="grid grid-cols-1 gap-2 px-5 py-4 md:grid-cols-2 lg:grid-cols-3">{insights.slice(0, 9).map((i) => <InsightCard key={i.id} i={i} />)}</div>}</Panel>
        <IssuesInsights issues={analytics.clusteredIssues} duplicates={analytics.duplicateGroups} />
        <PRInsights prs={analytics.prRisks} />
        <ContributorsInsights contribs={analytics.contributorAnalytics} busFactor={analytics.busFactor} />
        <ActivityTrends buckets={analytics.activityBuckets} />
        <Panel><SectionHeader title="Languages" /><LanguageBar langs={langs} /></Panel>
        <CodebaseSignals signals={analytics.codebaseSignals} />
        <SecurityPanel issues={analytics.clusteredIssues} insights={insights} repoInfo={{ license: r.license?.spdx_id ?? null, archived: r.archived, disabled: r.disabled }} />
        {fixes.length > 0 && <div className="space-y-4"><Panel><SectionHeader title="AI Fix Proposals" sub={`${fixes.length} generated`} /></Panel>{fixes.slice(0, 5).map((fix) => <FixCard key={fix.id} fix={fix} />)}</div>}
        <p className="text-xs text-text-dim text-center">Generated by TraceRoot \u00b7 Data from <ExternalLink href={`https://github.com/${r.full_name}`}>github.com/{r.full_name}</ExternalLink></p>
      </div>
    </div>
  );
}
